<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    targetNamespace="http://dkansh.org/services/BookingService/"
    xmlns:tns="http://dkansh.org/services/BookingService/" xmlns:booking="http://dkansh.org/entities/Booking"
    name="BookingService">
 
    <wsdl:types>
        <xsd:schema targetNamespace="http://dkansh.org/services/BookingService/">
            <xsd:import namespace="http://dkansh.org/entities/Booking"
                schemaLocation="../entities/booking.xsd" />
        </xsd:schema>
    </wsdl:types>
 
    <wsdl:message name="BookingRequest">
        <wsdl:part element="booking:BookingRequestType" name="parameters" />
    </wsdl:message>
    <wsdl:message name="BookingResponse">
        <wsdl:part element="booking:BookingResponseType" name="parameters" />
    </wsdl:message>
 
    <wsdl:portType name="IBookingService">
        <wsdl:operation name="bookTicket">
            <wsdl:input message="tns:BookingRequest" />
            <wsdl:output message="tns:BookingResponse" />
        </wsdl:operation>
    </wsdl:portType>
 
    <wsdl:binding name="BookingServiceSOAPBinding" type="tns:IBookingService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="bookTicket">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
 
    <wsdl:service name="BookingService">
        <wsdl:port name="BookingServicePort" binding="tns:BookingServiceSOAPBinding">
            <soap:address
                location="http://localhost:8080/SimpleSOAPProgram/services/BookingService" />
        </wsdl:port>
    </wsdl:service>
    
    <wsdl:service name="BookingService2">
        <wsdl:port name="BookingServicePort" binding="tns:BookingServiceSOAPBinding">
            <soap:address
                location="http://localhost:8080/SimpleSOAPProgram/services/BookingService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>